-- El fondo del hilo, elegido por cada persona y no por el grupo.
--
-- Va en la membresía y no en la conversación a propósito: es una preferencia de
-- quien mira, como `muted` o `archived`. En la conversación, un miembro podría
-- cambiarle el fondo a los demás.
--
-- Sin valor por defecto: NULL es «sin fondo», que es justo lo que tenían todas
-- las filas hasta ahora. Así la migración no reescribe nada.
-- `conversation_members` y no `ConversationMember`: en el esquema el modelo se
-- llama así, pero la tabla lleva `@@map`. Escribí el nombre del modelo y CI lo
-- cazó al aplicar las migraciones sobre una base limpia, que es exactamente
-- para lo que está ese paso — el resto de comprobaciones pasaban.
ALTER TABLE "conversation_members" ADD COLUMN "background" TEXT;
